# frontend-deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fe-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: fe
#   template:
#     metadata:
#       labels:
#         app: fe
#     spec:
#       containers:
#       - name: fe
#         image: nhutlinh231/frontend-k8s
#         ports:
#         - containerPort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deploy
  labels: 
    app: myapp
    type: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec: 
      containers:
      - name: fe
        image: nhutlinh231/frontend-k8s
        ports:
        - containerPort: 3000
          resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fe-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: fe
#   template:
#     metadata:
#       labels:
#         app: fe
#     spec:
#       containers:
#       - name: fe
#         image: nhutlinh231/frontend-k8s
#         ports:
#         - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  type: NodePort
  selector:
    app: fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
